### ISSUE TITLE
could not find function "concord_naics_isic"

### ISSUE THREAD

**Issue by QWangPKU** [insongkim/concordance#17]
Hi,

Thanks for building this amazing package! I am new to this and just installed the package today. I want to translate from different versions of 6-digit NAICS to ISIC.3.1 and get the weight of each of those matches.

It seems that there is function "concord_naics_isic" in the package when I run the code below. Do you know how to call this function and do what I intended? Thank you!

~~~
> library(concordance)
> concord_naics_isic(sourcevar = c("11998"),
+                    origin = "NAICS2012", destination = "ISIC3.1",
+                    dest.digit = 4, all = TRUE)
Error in concord_naics_isic(sourcevar = c("11998"), origin = "NAICS2012",  : 
  could not find function "concord_naics_isic"
~~~

QW

**Comment by stevenliaotw** [comment]
Hi QW,

Thanks for your interest in our package! ISIC-related code support should
be in the developer's version of the package. See installation instructions
here (
https://github.com/insongkim/concordance?tab=readme-ov-file#installation-instructions).
Let me know if that fixes the issue.

Also, we usually use the main wrapper function “concord” instead of the
underlying sub-functions like “concord_naics_isic” to make everything
easier.

Best,
Steven

Steven Liao
Associate Professor
Department of Political Science
University of California, Riverside
http://www.stevenliao.org/

**Comment by QWangPKU** [comment]
Thank you so much! I can make it work now. If I run this over a full list of NAICS, is there a suggested way to export the matched codes and weights to a long table in csv? I can do it in a straightforward but slow way (e.g. extract the elements from the list and put it into a matrix and then export to a csv), but still wonder if you have better suggestions.

**Comment by stevenliaotw** [comment]
No problem! I usually use the purrr:pluck function to extract
elements/vectors and transform that into whatever format I need. Should be
pretty fast too.

Steven Liao
Associate Professor
Department of Political Science
University of California, Riverside
http://www.stevenliao.org/

**Comment by QWangPKU** [comment]
Thank you, Steven! This is very helpful.
