### ISSUE TITLE
Question about including HS 2022

### ISSUE THREAD

**Issue by tomoya-sasaki** [insongkim/concordance#7]
Thank you so much for building this great package. This has helped my research a lot. 

I am wondering when you plan to include the newest HS 2022 in this package. The correlation table and description are available here in PDF format (unfortunately). 
https://www.trade.gov/harmonized-system-hs-codes#:~:text=Among%20industry%20classification%20systems%2C%20Harmonized,method%20of%20classifying%20traded%20products.

Thanks in advance.

**Comment by stevenliaotw** [comment]
Hi Tomoya,

Glad to hear that the package has been helpful for your research! Since concordances are needed not only within the HS classification but also between HS and other classifications (SITC, ISIC, etc.), we have been relying on the official tables from WITS <https://wits.worldbank.org/product_concordance.html> and UN Trade Stats <https://unstats.un.org/unsd/trade/classifications/correspondence-tables.asp>. Thus, we will need to wait until those tables come out to incorporate the newest HS 2022. 

I know you work with In Song, so if this is something you would be interested in contributing to the package, e-mail me and we can chat more. 

Steven

**Comment by tomoya-sasaki** [comment]
Thank you @stevenliaotw! At this moment, I am not sure if we will use the newest HS 2022 for the project with In Song. However, I am definitely interested in contributing to this package if there is anything I can help improve this package.

**Comment by stevenliaotw** [comment]
Sounds good! Will let you know.
